server.port=8080
server.forward-headers-strategy=framework
spring.application.name=satya-certificate-system

# =========================
# POSTGRESQL DATABASE
# =========================

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/certificate_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:satyaprakashtripathi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1974}

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# FRONTEND URL
# =========================

app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# =========================
# ADMIN LOGIN
# =========================

app.admin-email=${ADMIN_EMAIL:electricalstudyworld@gmail.com}
app.admin-default-password=${ADMIN_PASSWORD:admin12345}

# =========================
# JWT CONFIG
# =========================

app.jwt-secret=${JWT_SECRET:change_this_secret_key_change_this_secret_key_1234567890}
app.jwt-expiration-ms=86400000

# =========================
# GMAIL SMTP
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:yourgmail@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your_app_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# GOOGLE OAUTH2
# =========================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# =========================
# GITHUB OAUTH2
# =========================

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email